services:
  redis:
    image: redis:7-alpine
    command: redis-server --maxmemory 512M --maxmemory-policy allkeys-lru --save "" --appendonly no
  web:
    build: .
    init: true
    environment:
      BOT_SLEEP_MS: ${BOT_SLEEP_MS:-61000}
    ports:
      - 8443:443
